language: node_js
node_js:
  - "6"
addons:
  code_climate:
    repo_token: 3b1b021b9d59d90022a8de77bbd32181b559735e3a650dde9da76e23253764e3
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - codeclimate-test-reporter < ./coverage/report-lcov/lcov.info
